### ISSUE TITLE
itoProcess.R

### ISSUE THREAD

**Issue by ghost** [shill1729/kellyfractions#1]
Sean I think line 66 needs to be updated since i cant find the function nor the pkg pdes::feynman_kac. 
Maybe fkpde::setupPDE?
Thanks again for the awesome work.
nico

**Comment by shill1729** [comment]
Hi Nico,
Thanks for reporting this. I had made the package pdes to replace fkpde and followed through with changes to kellyfractions. Back then (a year or two) I did not expect many people to use this so just I forgot to actually make a public repo for the pkg pdes. But I will rectify that now. Thanks for using the package!

**Comment by ghost** [comment]
Thank you very much and really appreciate your support. Nico

**Comment by shill1729** [comment]
Okay [pdes](https://github.com/shill1729/pdes) is up and I fixed some bugs in kellyfractions and just tested the example in the readme. I will try to add more examples this week too. Let me know if it works.

**Comment by ghost** [comment]
Sean quick question for my class I am thinking of sharing your kellyfractions pkg with students so they use it for a crypto trading competition I will be sponsoring. Any example will be much appreciated. Nico

**Comment by shill1729** [comment]
As far as real-world use of the functions in this package for deciding investment allocations and portfolios—I cannot offer any advice or examples. Instead, as a warning, it should be noted that the mathematical models implemented in this package are _highly idealized_ and therefore should be used _at your own risk_. However, if you have questions about arguments/inputs of certain functions in this package or would like references for the mathematical models, I am more than willing to provide support.

**Comment by ghost** [comment]
Thank you Sean. I may get back to you with questions. Sincerely, Nico
